version: '3.1'
services:
  db_cars:
    image: postgres:13
    container_name: "db_cars"
    ports:
      - "5432:5432"
    networks:
      - cars_network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  cars:
    build: .
    container_name: "cars_directory"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cars_network
    environment:
      - spring.datasource.url=jdbc:postgresql://db_cars:5432/postgres
networks:
  cars_network:








